server:
  port: 9001

spring:
  application:
    name: cloud-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.8.7:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"