server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server

# 单机版
#eureka:
#  instance:
#    #eureka服务端实例名称
#    hostname: localhost
#  client:
#    #表示不向注册中心注册自己
#    register-with-eureka: false
#    #false表示自己就是注册中心，我的职责就是维护服务实例,并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      # 设置与eureka server交互的地址查询服务和注册服务都需要这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 集群版
eureka:
  instance:
    #eureka服务端实例名称
    hostname: 127.0.0.1
    #所在主机ip 都在自己机子上注意区分不同ip
    ip-address: 127.0.0.12
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    #指定实例id
    instance-id: ${spring.application.name}:${server.port}
  client:
    #表示是否向注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责就是维护服务实例,并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://127.0.0.1:7001/eureka/