server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.8.7:3306/db2019?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: dev
    password: productdev123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.clownfish7.springcloud.entity