server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server

# 单机版
#eureka:
#  instance:
#    #eureka服务端实例名称
#    hostname: localhost
#  client:
#    #表示不向注册中心注册自己
#    register-with-eureka: false
#    #false表示自己就是注册中心，我的职责就是维护服务实例,并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      # 设置与eureka server交互的地址查询服务和注册服务都需要这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 集群版
eureka:
  instance:
    #eureka服务端实例名称
    hostname: 127.0.0.1
    #所在主机ip 都在自己机子上注意区分不同ip
    ip-address: 127.0.0.11
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    #指定实例id
    instance-id: ${spring.application.name}:${server.port}
    #eureka客户端向服务端发送心跳时间间隔，默认30s
    lease-renewal-interval-in-seconds: 30
    #eureka服务端在收到最后一次心跳后的等待时间，超时将删除服务，90s
    lease-expiration-duration-in-seconds: 90
  client:
    #表示是否向注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责就是维护服务实例,并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://127.0.0.1:7002/eureka/
  server:
    #是否开启自我保护机制，默认为true
    enable-self-preservation: true
    #清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 60000