server:
  port: 8401

spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.8.7:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        #sentinel默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
        port: 8719
        clientIp: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"