server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery: #Nacos注册中心地址
        server-addr: 47.97.8.7:8848
    sentinel:
      transport: #dashboard地址
        dashboard: localhost:8080
        port: 8719  #默认端口，如果被占用则从8719依次+1扫描
      datasource:
        ds1:
          nacos:
            server-addr: 47.97.8.7:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


service-url:
  nacos-user-service: http://nacos-payment-provider

feign:
  sentinel:
    enabled: true