server:
  port: 83

spring:
  application:
    name: cloud-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.8.7:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://cloud-payment-service